import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()

function read(relativePath: string) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('SpacesView reframes graph spaces as memory spaces', () => {
  const file = read('frontend/src/components/SpacesView.vue')

  assert.match(file, /你的材料，按问题长成记忆空间/)
  assert.match(file, /<p class="eyebrow">知识库<\/p>/)
  assert.match(file, /const color = ref\('#b0501e'\)/)
  assert.doesNotMatch(file, /const color = ref\('#315f9f'\)/)
  assert.match(file, /memory-quick-actions/)
  assert.match(file, /问过去的你/)
  assert.match(file, /收下一份材料/)
  assert.match(file, /打开主记忆/)
  assert.match(file, /openDefaultSpace/)
  assert.match(file, /startCollect/)
  assert.match(file, /spaceDisplayName/)
  assert.match(file, /待整理/)
  assert.match(file, /主记忆/)
  assert.match(file, /displayName: spaceDisplayName\(space\)/)
  assert.match(file, /<strong>{{ spaceCard.displayName }}<\/strong>/)
  assert.doesNotMatch(file, /<strong>{{ spaceCard.name }}<\/strong>/)
  assert.match(file, /graph-space-card/)
  assert.match(file, /新材料会先放在这里，等待确认和整理。/)
  assert.match(file, /默认记忆空间，保存当前 SnapGraph 工作流的主要材料、判断和开放问题。/)
  assert.match(file, /进入空间/)
  assert.match(file, /新建记忆空间/)
  assert.match(file, /返回知识库/)
  assert.match(file, /最近材料/)
})

test('GraphSpaceView adds overview mode and preserves workbench mode', () => {
  const file = read('frontend/src/components/GraphSpaceView.vue')

  assert.match(file, /graph-overview-mode/)
  assert.match(file, /spaceDisplayName/)
  assert.match(file, /<h2>{{ spaceDisplayName }}<\/h2>/)
  assert.doesNotMatch(file, /<h2>{{ space.name }}<\/h2>/)
  assert.match(file, /const editSpaceColor = ref\('#b0501e'\)/)
  assert.doesNotMatch(file, /const editSpaceColor = ref\('#315f9f'\)/)
  assert.match(file, /知识库 \/ 记忆云/)
  assert.match(file, /记忆云/)
  assert.match(file, /知识库视图切换/)
  assert.match(file, /高级审计/)
  assert.match(file, /const surfaceMode = ref<GraphSurfaceMode>\('overview'\)/)
  assert.match(file, /graphHeaderStats/)
  assert.match(file, /graph-guided-actions/)
  assert.match(file, /找回旧判断/)
  assert.match(file, /先问一句过去的你/)
  assert.match(file, /继续处理/)
  assert.match(file, /最近证据/)
  assert.match(file, /这个空间的主题/)
  assert.match(file, /待处理线索/)
  assert.match(file, /这个空间能帮你找回什么/)
  assert.match(file, /查看这个空间里材料、想法和项目之间的整体结构。/)
  assert.match(file, /查看某个回答或判断背后的证据路径。/)
  assert.match(file, /查看开放问题、下一步和待处理连接。/)
})

test('GraphSpaceView sanitizes runtime route suggestion copy for built-in spaces', () => {
  const file = read('frontend/src/components/GraphSpaceView.vue')

  assert.match(file, /routeSuggestionReasonText/)
  assert.match(file, /sanitizeBuiltInSpaceNames/)
  assert.match(file, /待整理/)
  assert.match(file, /主记忆/)
  assert.match(file, /<p>{{ routeSuggestionReasonText\(suggestion\) }}<\/p>/)
  assert.match(file, /title: routeSuggestionReasonText\(suggestion\)/)
  assert.doesNotMatch(file, /<p>{{ suggestion.reason }}<\/p>/)
  assert.doesNotMatch(file, /title: suggestion.reason/)
})

test('GraphSpaceView turns search history into a novice-friendly memory cloud', () => {
  const file = read('frontend/src/components/GraphSpaceView.vue')

  assert.match(file, /questions: SavedQuestion\[\]/)
  assert.match(file, /graphSearchQuery/)
  assert.match(file, /memory-cloud-console/)
  assert.match(file, /搜一个词，找过去的证据/)
  assert.match(file, /相关线索会一起亮起/)
  assert.match(file, /搜关键词，匹配的点会亮起来/)
  assert.match(file, /cloudItems/)
  assert.match(file, /future_recall_questions/)
  assert.match(file, /保存过的问题/)
  assert.match(file, /证据来源/)
  assert.match(file, /继续从这里追问/)
  assert.match(file, /askFromCloud/)
  assert.match(file, /focusCloudItem/)
})

test('GraphSpaceView renders the HermesPet-style search constellation instead of literal cloud pills', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /const CLOUD_DRAG_THRESHOLD = 4/)
  assert.match(view, /cloudDragOffsets/)
  assert.match(view, /draggingCloudKey/)
  assert.match(view, /cloudOrbitElement/)
  assert.match(view, /cloudConstellationEdges/)
  assert.match(view, /cloudGraphPoint/)
  assert.match(view, /syncCloudOrbitSize/)
  assert.match(view, /ResizeObserver/)
  assert.match(view, /startCloudDrag/)
  assert.match(view, /moveCloudDrag/)
  assert.match(view, /endCloudDrag/)
  assert.match(view, /cancelCloudDrag/)
  assert.match(view, /setPointerCapture/)
  assert.match(view, /cloud-constellation/)
  assert.match(view, /cloud-constellation-edges/)
  assert.match(view, /cloud-focus-label/)
  assert.match(view, /cloud-helper-pill/)
  assert.match(view, /搜关键词，匹配的点会亮起来/)
  assert.match(view, /相关线索会一起亮起/)
  assert.match(view, /@click="selectCloudNode\(\$event, item\)"/)
  assert.match(view, /@pointerdown\.stop="startCloudDrag\(\$event, item\)"/)
  assert.match(view, /@pointermove\.stop="moveCloudDrag\(\$event\)"/)
  assert.match(view, /@pointerup\.stop="endCloudDrag"/)
  assert.match(view, /@pointercancel\.stop="cancelCloudDrag"/)
  assert.doesNotMatch(view, /@mousedown\.stop="startCloudMouseDrag/)
  assert.doesNotMatch(view, /moveCloudMouseDrag/)
  assert.match(view, /--cloud-drag-x/)
  assert.match(view, /--cloud-drag-y/)
  assert.doesNotMatch(view, /cloud-node-body/)

  assert.match(styles, /\.cloud-constellation/)
  assert.match(styles, /\.cloud-constellation-edges/)
  assert.match(styles, /\.cloud-focus-label/)
  assert.match(styles, /\.cloud-helper-pill/)
  assert.match(styles, /\.cloud-node-dot/)
  assert.match(styles, /\.cloud-node-halo/)
  assert.match(styles, /\.cloud-node\.is-dragging/)
  assert.match(styles, /scale\(1\.08\)/)
  assert.match(styles, /cubic-bezier\(0\.16, 1\.18, 0\.32, 1\)/)
  assert.match(styles, /knowledge-nebula-bloom/)
  assert.match(styles, /rgba\(10, 13, 18, 0\.96\)/)
  assert.doesNotMatch(styles, /cloud-node-body::before/)
})

test('GraphSpaceView gives the memory cloud a HermesPet-like nebula depth', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /记忆星图/)
  assert.match(view, /搜索历史星图/)
  assert.match(view, /每条线索都是一颗星/)
  assert.match(styles, /\.cloud-constellation\s*{[\s\S]*animation: knowledge-nebula-bloom/)
  assert.match(styles, /radial-gradient\(circle at 50% 47%, rgba\(255, 229, 156, 0\.24\), transparent 13%\)/)
  assert.match(styles, /linear-gradient\(180deg, rgba\(10, 13, 18, 0\.96\), rgba\(26, 28, 32, 0\.94\)\)/)
  assert.match(styles, /\.cloud-node-dot\s*{[\s\S]*box-shadow:[\s\S]*0 0 30px/)
  assert.match(styles, /\.cloud-constellation-edges line\s*{[\s\S]*stroke: rgba\(214, 198, 143, 0\.18\)/)
  assert.match(styles, /@keyframes knowledge-nebula-bloom/)
})

test('GraphSpaceView gives the constellation HermesPet-like elastic drag behavior', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /cloudDragInfluenceOffsets/)
  assert.match(view, /CLOUD_DRAG_INFLUENCE_PULL/)
  assert.match(view, /cloudElasticInfluence/)
  assert.match(view, /cloudInfluenceOffset/)
  assert.match(view, /attachCloudDragListeners/)
  assert.match(view, /detachCloudDragListeners/)
  assert.match(view, /x: roundCloudMotion\(deltaX \* strength \* CLOUD_DRAG_INFLUENCE_PULL\)/)
  assert.match(view, /y: roundCloudMotion\(deltaY \* strength \* CLOUD_DRAG_INFLUENCE_PULL\)/)
  assert.match(view, /window\.addEventListener\('pointerup', endCloudDrag/)
  assert.match(view, /window\.addEventListener\('pointercancel', cancelCloudDrag/)
  assert.doesNotMatch(view, /window\.addEventListener\('mousemove', moveCloudMouseDrag/)
  assert.doesNotMatch(view, /window\.addEventListener\('mouseup', endCloudMouseDrag/)
  assert.doesNotMatch(view, /@mousedown\.stop="startCloudMouseDrag\(\$event, item\)"/)
  assert.doesNotMatch(view, /CLOUD_MOUSE_POINTER_ID/)
  assert.match(view, /@lostpointercapture\.stop="handleCloudLostPointerCapture\(\$event\)"/)
  assert.match(view, /is-cloud-dragging/)
  assert.match(view, /is-linked/)
  assert.match(view, /selectedCloudKey\.value = item\.key/)

  assert.match(styles, /\.cloud-constellation\.is-cloud-dragging/)
  assert.match(styles, /\.cloud-node\.is-linked/)
  assert.match(styles, /scale\(1\.08\)/)
  assert.match(styles, /cubic-bezier\(0\.16, 1\.18, 0\.32, 1\)/)
  assert.match(styles, /filter: blur\(22px\)/)
  assert.match(styles, /\.cloud-constellation\.is-cloud-dragging \.cloud-constellation-edges line\.active/)
})

test('GraphSpaceView opens the original saved question and answer from a star click', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const types = read('frontend/src/types.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /export type SavedQuestionDetail/)
  assert.match(types, /answer: string/)
  assert.match(view, /questionId\?: string/)
  assert.match(view, /const selectedQuestionDetail = ref<SavedQuestionDetail \| null>\(null\)/)
  assert.match(view, /openCloudQuestionHistory/)
  assert.match(view, /api<SavedQuestionDetail>\(`\/api\/questions\/\$\{encodeURIComponent\(item\.questionId\)\}`\)/)
  assert.match(view, /selectCloudNode\(event: MouseEvent, item: CloudItem\)/)
  assert.match(view, /shouldSuppressCloudClick\(item\)/)
  assert.match(view, /cloud-history-panel/)
  assert.match(view, /当初的问题/)
  assert.match(view, /当初的回答/)
  assert.match(view, /继续从这里追问/)
  assert.match(view, /item\.kind === 'question'/)
  assert.match(view, /suppressCloudClick\(drag\.key\)/)
  assert.doesNotMatch(view, /askFromCloud\(selectedCloudItem\)/)
  assert.match(styles, /\.cloud-history-panel/)
  assert.match(styles, /\.cloud-history-answer/)
  assert.match(styles, /\.cloud-history-panel\.is-loading/)
})

test('GraphSpaceView keeps nebula dragging fluid with global motion and release recoil', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /CLOUD_SPRING_RESPONSE/)
  assert.match(view, /CLOUD_SPRING_DAMPING/)
  assert.match(view, /CLOUD_SPRING_SETTLE_MS/)
  assert.match(view, /CLOUD_CLICK_SUPPRESSION_MS/)
  assert.match(view, /cloudRecoilOffsets/)
  assert.match(view, /cloudRecoilKey/)
  assert.match(view, /cloudReturnKey/)
  assert.match(view, /pendingCloudDragFrame/)
  assert.match(view, /window\.requestAnimationFrame\(applyPendingCloudDragFrame\)/)
  assert.match(view, /cloudReturnStartTimer/)
  assert.match(view, /cloudReturnTimer/)
  assert.match(view, /startCloudSpringReturn/)
  assert.match(view, /settleCloudSpringReturn/)
  assert.match(view, /captureCloudReleaseOffsets/)
  assert.match(view, /cloudDragOffsets\.value = Object\.fromEntries\([\s\S]*x: 0,\s*y: 0/)
  assert.match(view, /window\.addEventListener\('pointermove', moveCloudDrag/)
  assert.doesNotMatch(view, /resetCloudDragOffset\(drag\.key\)/)
  assert.doesNotMatch(view, /clampCloudDrag/)
  assert.doesNotMatch(view, /window\.requestAnimationFrame\(stepCloudSpringReturn\)/)
  assert.match(view, /startCloudSpringReturn\(drag\.key, releaseOffsets\)/)
  assert.match(view, /x: 0,\s*y: 0,\s*strength/)
  assert.match(view, /clearCloudRecoil/)
  assert.match(view, /clearCloudReturn/)
  assert.match(view, /'is-recoiling'/)
  assert.match(view, /'is-returning'/)
  assert.match(view, /'is-cloud-recoiling'/)
  assert.match(view, /'is-cloud-returning'/)

  assert.match(styles, /\.cloud-constellation\.is-cloud-recoiling/)
  assert.match(styles, /\.cloud-constellation\.is-cloud-returning/)
  assert.match(styles, /\.cloud-constellation\.is-cloud-dragging \.cloud-node:not\(\.is-dragging\)/)
  assert.match(styles, /\.cloud-node\.is-recoiling/)
  assert.match(styles, /\.cloud-node\.is-returning/)
  assert.match(styles, /cubic-bezier\(0\.22, 1, 0\.36, 1\)/)
  assert.match(styles, /\.cloud-node\.is-linked \.cloud-node-halo/)
})

test('GraphSpaceView makes the nebula the primary full-width graph entry', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /class="cloud-inspector-card cloud-context-dock"/)
  assert.match(styles, /\.memory-cloud-layout\s*{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/)
  assert.match(styles, /\.cloud-constellation\s*{[\s\S]*min-height: 520px/)
  assert.match(styles, /\.cloud-inspector-card\.cloud-context-dock\s*{[\s\S]*grid-template-columns: minmax\(0, 1\.2fr\) minmax\(210px, 0\.8fr\) auto/)
  assert.match(styles, /\.cloud-inspector-card\.cloud-context-dock \.cloud-actions\s*{[\s\S]*grid-column: 3/)
  assert.match(styles, /@media \(max-width: 900px\)[\s\S]*\.cloud-inspector-card\.cloud-context-dock\s*{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/)
  assert.doesNotMatch(styles, /grid-template-columns: minmax\(0, 1\.35fr\) minmax\(260px, 0\.85fr\)/)
})

test('styles keep the graph overview header compact so the nebula reaches the first viewport', () => {
  const styles = read('frontend/src/styles.css')

  assert.match(styles, /\.graph-space-detail \.space-detail-head\s*{[\s\S]*padding-bottom: 12px/)
  assert.match(styles, /\.graph-space-detail \.space-detail-head h2\s*{[\s\S]*font-size: clamp\(1\.25rem, 2vw, 1\.65rem\)/)
  assert.match(styles, /\.graph-space-detail \.space-detail-head p\s*{[\s\S]*-webkit-line-clamp: 2/)
  assert.match(styles, /\.graph-space-detail \.space-detail-topbar\s*{[\s\S]*min-width: max-content/)
  assert.match(styles, /\.graph-space-detail \.graph-space-stats\s*{[\s\S]*flex-wrap: nowrap/)
  assert.match(styles, /\.graph-space-detail \.graph-stat-chip\s*{[\s\S]*white-space: nowrap/)
  assert.match(styles, /\.memory-cloud-head p\s*{[\s\S]*-webkit-line-clamp: 2/)
  assert.match(styles, /\.memory-cloud-console\s*{[\s\S]*padding: 14px/)
})

test('styles keep guided actions compact until phone width so the nebula stays visible early', () => {
  const styles = read('frontend/src/styles.css')
  const tabletStart = styles.indexOf('@media (max-width: 1020px)')
  const phoneStart = styles.indexOf('@media (max-width: 760px)')
  const tabletSection = styles.slice(tabletStart, phoneStart)
  const phoneSection = styles.slice(phoneStart)

  assert.doesNotMatch(tabletSection, /\.graph-guided-actions\s*{[\s\S]*grid-template-columns: 1fr/)
  assert.match(phoneSection, /\.graph-guided-actions\s*{[\s\S]*grid-template-columns: 1fr/)
})

test('App fetches saved questions and passes them into the graph cloud', () => {
  const app = read('frontend/src/App.vue')
  const spaces = read('frontend/src/components/SpacesView.vue')

  assert.match(app, /SavedQuestion/)
  assert.match(app, /const savedQuestions = ref<SavedQuestion\[\]>\(\[\]\)/)
  assert.match(app, /loadQuestions/)
  assert.match(app, /api<SavedQuestion\[\]>\('\/api\/questions'\)/)
  assert.match(app, /:questions="savedQuestions"/)
  assert.match(spaces, /questions: SavedQuestion\[\]/)
  assert.match(spaces, /:questions="questions"/)
})

test('App treats visualization as a knowledge-internal view instead of a duplicate nav item', () => {
  const app = read('frontend/src/App.vue')

  assert.match(app, /type ActiveView = 'recall' \| 'spaces' \| 'collect'/)
  assert.match(app, /label: '知识库'/)
  assert.doesNotMatch(app, /label: '可视化'/)
  assert.doesNotMatch(app, /activeView === 'visualize'/)
  assert.doesNotMatch(app, /图谱可视化/)
})

test('App lets the knowledge overview route novice actions into collect and recall', () => {
  const app = read('frontend/src/App.vue')
  const spaces = read('frontend/src/components/SpacesView.vue')

  assert.match(app, /@start-collect="startCollect"/)
  assert.match(app, /function startCollect\(\)/)
  assert.match(app, /activeView\.value = 'collect'/)
  assert.match(spaces, /startCollect: \[\]/)
  assert.match(spaces, /\$emit\('startCollect'\)/)
})

test('App uses user-facing memory space names in the shell title', () => {
  const app = read('frontend/src/App.vue')

  assert.match(app, /function graphSpaceDisplayName/)
  assert.match(app, /if \(selectedSpaceId\.value === 'all'\) return '全部记忆'/)
  assert.match(app, /待整理/)
  assert.match(app, /主记忆/)
  assert.match(app, /graphSpaceDisplayName\(space\)/)
  assert.doesNotMatch(app, /全部图谱/)
  assert.doesNotMatch(app, /spaces\.value\.find\(.*\)\?\.name \|\| '图谱空间'/)
})

test('styles include phase 2B graph overview and mode switch classes', () => {
  const file = read('frontend/src/styles.css')

  assert.match(file, /\.memory-quick-actions/)
  assert.match(file, /\.memory-quick-action/)
  assert.match(file, /\.graph-space-card/)
  assert.match(file, /\.graph-space-stats/)
  assert.match(file, /\.graph-overview-mode/)
  assert.match(file, /\.graph-summary-card/)
  assert.match(file, /\.graph-mode-switch/)
  assert.match(file, /\.graph-workbench/)
  assert.match(file, /\.graph-stat-chip/)
  assert.match(file, /\.graph-recent-source-card/)
  assert.match(file, /\.graph-key-node-card/)
  assert.match(file, /\.open-loop-card/)
  assert.match(file, /\.graph-empty-inspector/)
  assert.match(file, /\.graph-guided-actions/)
  assert.match(file, /\.graph-guided-action/)
  assert.match(file, /\.space-question-starters/)
})

test('styles include the search-history memory cloud surface', () => {
  const file = read('frontend/src/styles.css')

  assert.match(file, /\.memory-cloud-console/)
  assert.match(file, /\.cloud-search-row/)
  assert.match(file, /\.cloud-orbit/)
  assert.match(file, /\.cloud-node/)
  assert.match(file, /\.cloud-node\.selected/)
  assert.match(file, /\.cloud-inspector-card/)
  assert.match(file, /\.cloud-evidence-list/)
  assert.match(file, /\.cloud-empty-state/)
})
