import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()

function read(relativePath: string) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('SpacesView reframes graph spaces as memory spaces', () => {
  const file = read('frontend/src/components/SpacesView.vue')

  assert.match(file, /你的材料，按问题长成记忆空间/)
  assert.match(file, /<p class="eyebrow">知识库<\/p>/)
  assert.match(file, /const color = ref\('#b0501e'\)/)
  assert.doesNotMatch(file, /const color = ref\('#315f9f'\)/)
  assert.match(file, /memory-quick-actions/)
  assert.match(file, /问过去的你/)
  assert.match(file, /收下一份材料/)
  assert.match(file, /打开主记忆/)
  assert.match(file, /openDefaultSpace/)
  assert.match(file, /startCollect/)
  assert.match(file, /spaceDisplayName/)
  assert.match(file, /待整理/)
  assert.match(file, /主记忆/)
  assert.match(file, /displayName: spaceDisplayName\(space\)/)
  assert.match(file, /<strong>{{ spaceCard.displayName }}<\/strong>/)
  assert.doesNotMatch(file, /<strong>{{ spaceCard.name }}<\/strong>/)
  assert.match(file, /graph-space-card/)
  assert.match(file, /新材料会先放在这里，等待确认和整理。/)
  assert.match(file, /默认记忆空间，保存当前 SnapGraph 工作流的主要材料、判断和开放问题。/)
  assert.match(file, /进入空间/)
  assert.match(file, /新建记忆空间/)
  assert.match(file, /返回知识库/)
  assert.match(file, /最近材料/)
})

test('GraphSpaceView adds overview mode and preserves workbench mode', () => {
  const file = read('frontend/src/components/GraphSpaceView.vue')

  assert.match(file, /graph-overview-mode/)
  assert.match(file, /spaceDisplayName/)
  assert.match(file, /<h2>{{ spaceDisplayName }}<\/h2>/)
  assert.doesNotMatch(file, /<h2>{{ space.name }}<\/h2>/)
  assert.match(file, /const editSpaceColor = ref\('#b0501e'\)/)
  assert.doesNotMatch(file, /const editSpaceColor = ref\('#315f9f'\)/)
  assert.match(file, /知识库 \/ 记忆云/)
  assert.match(file, /记忆云/)
  assert.match(file, /知识库视图切换/)
  assert.match(file, /高级审计/)
  assert.match(file, /const surfaceMode = ref<GraphSurfaceMode>\('overview'\)/)
  assert.match(file, /graphHeaderStats/)
  assert.match(file, /graph-guided-actions/)
  assert.match(file, /找回旧判断/)
  assert.match(file, /先问一句过去的你/)
  assert.match(file, /继续处理/)
  assert.match(file, /最近证据/)
  assert.match(file, /这个空间的主题/)
  assert.match(file, /待处理线索/)
  assert.match(file, /这个空间能帮你找回什么/)
  assert.match(file, /查看这个空间里材料、想法和项目之间的整体结构。/)
  assert.match(file, /查看某个回答或判断背后的证据路径。/)
  assert.match(file, /查看开放问题、下一步和待处理连接。/)
})

test('GraphSpaceView adds a design-thinking needs review queue to the space overview', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const panel = read('frontend/src/components/ReviewQueuePanel.vue')
  const queueTypes = read('frontend/src/components/reviewQueueTypes.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(queueTypes, /export type ReviewQueueItemKind/)
  assert.match(queueTypes, /'ai-inference'/)
  assert.match(queueTypes, /'weak-path'/)
  assert.match(queueTypes, /'route-suggestion'/)
  assert.match(queueTypes, /'open-loop'/)
  assert.match(queueTypes, /export type ReviewQueueItem/)
  assert.match(queueTypes, /validationQuestion: string/)

  assert.match(view, /import ReviewQueuePanel/)
  assert.match(view, /reviewQueueItems/)
  assert.match(view, /low_confidence_contexts/)
  assert.match(view, /high_value_review_paths/)
  assert.match(view, /open_loop_hotspots/)
  assert.match(view, /routeSuggestionReasonText/)
  assert.match(view, /<ReviewQueuePanel/)
  assert.match(view, /:items="reviewQueueItems"/)
  assert.match(view, /@ask="askReviewQueueItem"/)
  assert.match(view, /@focus-source="focusReviewQueueSource"/)
  assert.match(view, /@open-audit="openReviewQueueAudit"/)
  assert.match(view, /function askReviewQueueItem\(item: ReviewQueueItem\)/)
  assert.match(view, /function focusReviewQueueSource\(item: ReviewQueueItem\)/)
  assert.match(view, /function openReviewQueueAudit\(item: ReviewQueueItem\)/)

  assert.match(panel, /Needs Review/)
  assert.match(panel, /需要验证的假设/)
  assert.match(panel, /验证问题/)
  assert.match(panel, /系统推断/)
  assert.match(panel, /弱证据路径/)
  assert.match(panel, /空间建议/)
  assert.match(panel, /开放问题/)
  assert.match(panel, /define-test-decide/)
  assert.match(panel, /emit\('ask', item\)/)
  assert.match(panel, /emit\('focusSource', item\)/)
  assert.match(panel, /emit\('openAudit', item\)/)

  assert.match(styles, /\.review-queue-panel/)
  assert.match(styles, /\.review-queue-card/)
  assert.match(styles, /\.review-queue-actions/)
  assert.match(styles, /\.review-queue-stage/)
})

test('GraphSpaceView adds an actionable AI inference review flow', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const panel = read('frontend/src/components/ReviewQueuePanel.vue')
  const decision = read('frontend/src/components/ReviewDecisionPanel.vue')
  const queueTypes = read('frontend/src/components/reviewQueueTypes.ts')
  const types = read('frontend/src/types.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /review_status\?: string/)
  assert.match(types, /review_note\?: string/)
  assert.match(types, /reviewed_at\?: string/)
  assert.match(queueTypes, /reviewStatus\?: string/)
  assert.match(queueTypes, /reviewNote\?: string/)
  assert.match(queueTypes, /originalWhySaved\?: string/)

  assert.match(panel, /ReviewDecisionPanel/)
  assert.match(panel, /selectedReviewItem/)
  assert.match(panel, /@decide="emit\('decide', \$event\)"/)
  assert.match(panel, /review-status-confirmed/)
  assert.match(panel, /review-status-rejected/)
  assert.match(panel, /review-status-deferred/)

  assert.match(decision, /AI 推断审查/)
  assert.match(decision, /确认/)
  assert.match(decision, /改写/)
  assert.match(decision, /拒绝/)
  assert.match(decision, /稍后处理/)
  assert.match(decision, /review_status: 'confirmed'/)
  assert.match(decision, /review_status: 'rewritten'/)
  assert.match(decision, /review_status: 'rejected'/)
  assert.match(decision, /review_status: 'deferred'/)
  assert.match(decision, /why_saved: rewriteText\.value\.trim\(\)/)
  assert.match(decision, /emit\('decide'/)

  assert.match(view, /@decide="reviewQueueDecision"/)
  assert.match(view, /function reviewQueueDecision\(decision: ReviewDecisionPayload\)/)
  assert.match(view, /\/api\/sources\/\$\{encodeURIComponent\(decision\.sourceId\)\}\/review/)
  assert.match(view, /PATCH/)
  assert.match(view, /updateSourceAfterReview/)
  assert.match(view, /isReviewResolved/)
  assert.match(view, /review_status/)
  assert.match(view, /review_note/)

  assert.match(styles, /\.review-decision-panel/)
  assert.match(styles, /\.review-decision-actions/)
  assert.match(styles, /\.review-rewrite-box/)
  assert.match(styles, /\.review-status-confirmed/)
})

test('GraphSpaceView sanitizes runtime route suggestion copy for built-in spaces', () => {
  const file = read('frontend/src/components/GraphSpaceView.vue')

  assert.match(file, /routeSuggestionReasonText/)
  assert.match(file, /sanitizeBuiltInSpaceNames/)
  assert.match(file, /待整理/)
  assert.match(file, /主记忆/)
  assert.match(file, /<p>{{ routeSuggestionReasonText\(suggestion\) }}<\/p>/)
  assert.match(file, /title: routeSuggestionReasonText\(suggestion\)/)
  assert.doesNotMatch(file, /<p>{{ suggestion.reason }}<\/p>/)
  assert.doesNotMatch(file, /title: suggestion.reason/)
})

test('GraphSpaceView turns search history into a novice-friendly memory cloud', () => {
  const file = read('frontend/src/components/GraphSpaceView.vue')
  const cloud = read('frontend/src/components/MemoryCloudConstellation.vue')

  assert.match(file, /questions: SavedQuestion\[\]/)
  assert.match(file, /graphSearchQuery/)
  assert.match(file, /memory-cloud-console/)
  assert.match(file, /搜一个词，找过去的证据/)
  assert.match(cloud, /相关线索会一起亮起/)
  assert.match(cloud, /搜关键词，匹配的点会亮起来/)
  assert.match(file, /cloudItems/)
  assert.match(file, /future_recall_questions/)
  assert.match(file, /保存过的问题/)
  assert.match(file, /证据来源/)
  assert.match(file, /继续从这里追问/)
  assert.match(file, /askFromCloud/)
  assert.match(file, /focusCloudItem/)
})

test('GraphSpaceView renders the HermesPet-style search constellation instead of literal cloud pills', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const cloud = read('frontend/src/components/MemoryCloudConstellation.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /import MemoryCloudConstellation/)
  assert.match(view, /<MemoryCloudConstellation/)
  assert.match(view, /:items="visibleCloudItems"/)
  assert.match(view, /v-model:search-query="graphSearchQuery"/)
  assert.match(view, /:selected-key="selectedCloudKey"/)
  assert.match(view, /@select="selectCloudNode"/)
  assert.match(view, /@update-selected-key="\$event => \(selectedCloudKey = \$event\)"/)
  assert.match(view, /@submit-search="askCloudSearch"/)
  assert.doesNotMatch(view, /const CLOUD_DRAG_THRESHOLD = 4/)
  assert.doesNotMatch(view, /window\.addEventListener\('pointermove', moveCloudDrag/)
  assert.doesNotMatch(view, /function startCloudDrag/)
  assert.match(cloud, /const CLOUD_DRAG_THRESHOLD = 4/)
  assert.match(cloud, /cloudDragOffsets/)
  assert.match(cloud, /draggingCloudKey/)
  assert.match(cloud, /cloudOrbitElement/)
  assert.match(cloud, /cloudConstellationEdges/)
  assert.match(cloud, /cloudGraphPoint/)
  assert.match(cloud, /const activeDrag = activeCloudDrag\.value\?\.active \? activeCloudDrag\.value : null/)
  assert.match(cloud, /props\.items\.find\(\(item\) => item\.key === activeDrag\.key\)/)
  assert.match(cloud, /syncCloudOrbitSize/)
  assert.match(cloud, /ResizeObserver/)
  assert.match(cloud, /startCloudDrag/)
  assert.match(cloud, /moveCloudDrag/)
  assert.match(cloud, /endCloudDrag/)
  assert.match(cloud, /cancelCloudDrag/)
  assert.match(cloud, /setPointerCapture/)
  assert.match(cloud, /cloud-constellation/)
  assert.match(cloud, /cloud-constellation-edges/)
  assert.match(cloud, /cloud-focus-label/)
  assert.match(cloud, /cloud-helper-pill/)
  assert.match(cloud, /搜关键词，匹配的点会亮起来/)
  assert.match(cloud, /相关线索会一起亮起/)
  assert.match(cloud, /@click="selectCloudNode\(\$event, item\)"/)
  assert.match(cloud, /@pointerdown\.stop="startCloudDrag\(\$event, item\)"/)
  assert.match(cloud, /@pointermove\.stop="moveCloudDrag\(\$event\)"/)
  assert.match(cloud, /@pointerup\.stop="endCloudDrag"/)
  assert.match(cloud, /@pointercancel\.stop="cancelCloudDrag"/)
  assert.doesNotMatch(cloud, /@mousedown\.stop="startCloudMouseDrag/)
  assert.doesNotMatch(cloud, /moveCloudMouseDrag/)
  assert.match(cloud, /--cloud-x/)
  assert.match(cloud, /--cloud-y/)
  assert.doesNotMatch(view, /cloud-node-body/)

  assert.match(styles, /\.cloud-constellation/)
  assert.match(styles, /\.cloud-constellation-edges/)
  assert.match(styles, /\.cloud-focus-label/)
  assert.match(styles, /\.cloud-helper-pill/)
  assert.match(styles, /\.cloud-node-dot/)
  assert.match(styles, /\.cloud-node-halo/)
  assert.match(styles, /\.cloud-node\.is-dragging/)
  assert.match(styles, /scale: 1\.08/)
  assert.match(styles, /--hermes-spring-drag: cubic-bezier\(0\.34, 1\.56, 0\.64, 1\)/)
  assert.match(styles, /knowledge-nebula-bloom/)
  assert.match(styles, /linear-gradient\(180deg, rgba\(255, 255, 255, 0\.94\), color-mix\(in srgb, var\(--secondary\) 64%, var\(--card\)\)\)/)
  assert.doesNotMatch(styles, /rgba\(10, 13, 18, 0\.96\)/)
  assert.doesNotMatch(styles, /cloud-node-body::before/)
})

test('GraphSpaceView gives the memory cloud StudyAgent paper depth with HermesPet colors', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const cloud = read('frontend/src/components/MemoryCloudConstellation.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /记忆星图/)
  assert.match(cloud, /搜索历史星图/)
  assert.match(view, /每条线索都是一颗星/)
  assert.match(styles, /\.cloud-constellation\s*{[\s\S]*animation: knowledge-nebula-bloom/)
  assert.match(styles, /background-size: 42px 42px, 42px 42px, auto, auto/)
  assert.match(styles, /color-mix\(in srgb, var\(--hermes-horse\) 18%, transparent\)/)
  assert.match(styles, /linear-gradient\(180deg, rgba\(255, 255, 255, 0\.94\), color-mix\(in srgb, var\(--secondary\) 64%, var\(--card\)\)\)/)
  assert.match(styles, /\.cloud-node-dot\s*{[\s\S]*box-shadow:[\s\S]*0 0 30px/)
  assert.match(styles, /\.cloud-constellation-edges line\s*{[\s\S]*stroke: color-mix\(in srgb, var\(--primary\) 18%, transparent\)/)
  assert.match(styles, /@keyframes knowledge-nebula-bloom/)
})

test('GraphSpaceView gives the constellation HermesPet-like elastic drag behavior', () => {
  const view = read('frontend/src/components/MemoryCloudConstellation.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /cloudDragInfluenceOffsets/)
  assert.match(view, /CLOUD_DRAG_INFLUENCE_PULL/)
  assert.match(view, /const CLOUD_DRAG_INFLUENCE_PULL = 0\.28/)
  assert.match(view, /\.slice\(0, 6\)/)
  assert.match(view, /cloudElasticInfluence/)
  assert.match(view, /cloudInfluenceOffset/)
  assert.match(view, /attachCloudDragListeners/)
  assert.match(view, /detachCloudDragListeners/)
  assert.match(view, /x: roundCloudMotion\(deltaX \* strength \* CLOUD_DRAG_INFLUENCE_PULL\)/)
  assert.match(view, /y: roundCloudMotion\(deltaY \* strength \* CLOUD_DRAG_INFLUENCE_PULL\)/)
  assert.match(view, /window\.addEventListener\('pointerup', endCloudDrag/)
  assert.match(view, /window\.addEventListener\('pointercancel', cancelCloudDrag/)
  assert.doesNotMatch(view, /window\.addEventListener\('mousemove', moveCloudMouseDrag/)
  assert.doesNotMatch(view, /window\.addEventListener\('mouseup', endCloudMouseDrag/)
  assert.doesNotMatch(view, /@mousedown\.stop="startCloudMouseDrag\(\$event, item\)"/)
  assert.doesNotMatch(view, /CLOUD_MOUSE_POINTER_ID/)
  assert.match(view, /@lostpointercapture\.stop="handleCloudLostPointerCapture\(\$event\)"/)
  assert.match(view, /is-cloud-dragging/)
  assert.match(view, /is-linked/)
  assert.match(view, /selectedCloudKey\.value = item\.key/)

  assert.match(styles, /\.cloud-constellation\.is-cloud-dragging/)
  assert.match(styles, /\.cloud-node\.is-linked/)
  assert.match(styles, /scale: 1\.08/)
  assert.match(styles, /var\(--hermes-spring-drag\)/)
  assert.match(styles, /--hermes-clawd: #de886d/)
  assert.match(styles, /--hermes-cloud: #7367d9/)
  assert.match(styles, /--hermes-horse: #e8c97a/)
  assert.match(styles, /filter: blur\(18px\)/)
  assert.match(styles, /--cloud-linked-scale/)
  assert.match(styles, /\.cloud-constellation\.is-cloud-dragging \.cloud-constellation-edges line\.active/)
})

test('GraphSpaceView opens the original saved question and answer from a star click', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const cloud = read('frontend/src/components/MemoryCloudConstellation.vue')
  const cloudTypes = read('frontend/src/components/memoryCloudTypes.ts')
  const types = read('frontend/src/types.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /export type SavedQuestionDetail/)
  assert.match(types, /answer: string/)
  assert.match(cloudTypes, /questionId\?: string/)
  assert.match(view, /const selectedQuestionDetail = ref<SavedQuestionDetail \| null>\(null\)/)
  assert.match(view, /openCloudQuestionHistory/)
  assert.match(view, /api<SavedQuestionDetail>\(`\/api\/questions\/\$\{encodeURIComponent\(item\.questionId\)\}`\)/)
  assert.match(view, /selectCloudNode\(event: MouseEvent, item: CloudItem\)/)
  assert.match(cloud, /shouldSuppressCloudClick\(item\)/)
  assert.match(view, /cloud-history-panel/)
  assert.match(view, /cloud-conversation-window/)
  assert.match(view, /cloud-chat-thread/)
  assert.match(view, /cloud-chat-message is-user/)
  assert.match(view, /cloud-chat-message is-assistant/)
  assert.match(view, /对话记录/)
  assert.match(view, /当初的问题/)
  assert.match(view, /当初的回答/)
  assert.match(view, /继续从这里追问/)
  assert.match(view, /item\.kind === 'question'/)
  assert.match(cloud, /suppressCloudClick\(drag\.key\)/)
  assert.doesNotMatch(view, /askFromCloud\(selectedCloudItem\)/)
  assert.match(styles, /\.cloud-history-panel/)
  assert.match(styles, /\.cloud-conversation-window/)
  assert.match(styles, /\.cloud-chat-bubble/)
  assert.match(styles, /\.cloud-history-panel\.is-loading/)
})

test('GraphSpaceView keeps nebula dragging fluid with global motion and release recoil', () => {
  const view = read('frontend/src/components/MemoryCloudConstellation.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /CLOUD_SPRING_RESPONSE/)
  assert.match(view, /CLOUD_SPRING_DAMPING/)
  assert.match(view, /CLOUD_SPRING_SETTLE_MS/)
  assert.match(view, /CLOUD_CLICK_SUPPRESSION_MS/)
  assert.match(view, /cloudRecoilOffsets/)
  assert.match(view, /cloudRecoilKey/)
  assert.match(view, /cloudReturnKey/)
  assert.match(view, /pendingCloudDragFrame/)
  assert.match(view, /window\.requestAnimationFrame\(applyPendingCloudDragFrame\)/)
  assert.match(view, /cloudSpringAnimationFrame/)
  assert.match(view, /cloudSpringStartedAt/)
  assert.match(view, /cloudSpringEntries/)
  assert.match(view, /startCloudSpringReturn/)
  assert.match(view, /stepCloudSpringReturn/)
  assert.match(view, /cloudSpringReturnMultiplier/)
  assert.match(view, /captureCloudReleaseOffsets/)
  assert.match(view, /window\.addEventListener\('pointermove', moveCloudDrag/)
  assert.doesNotMatch(view, /resetCloudDragOffset\(drag\.key\)/)
  assert.doesNotMatch(view, /clampCloudDrag/)
  assert.match(view, /window\.requestAnimationFrame\(stepCloudSpringReturn\)/)
  assert.match(view, /startCloudSpringReturn\(drag\.key, releaseOffsets\)/)
  assert.match(view, /nextOffsets\[entryKey\] = \{ x, y \}/)
  assert.match(view, /clearCloudRecoil/)
  assert.match(view, /clearCloudReturn/)
  assert.match(view, /'is-recoiling'/)
  assert.match(view, /'is-returning'/)
  assert.match(view, /'is-cloud-recoiling'/)
  assert.match(view, /'is-cloud-returning'/)

  assert.match(styles, /\.cloud-constellation\.is-cloud-recoiling/)
  assert.match(styles, /\.cloud-constellation\.is-cloud-returning/)
  assert.match(styles, /\.cloud-constellation\.is-cloud-dragging \.cloud-node:not\(\.is-dragging\)/)
  assert.match(styles, /\.cloud-node\.is-recoiling/)
  assert.match(styles, /\.cloud-node\.is-returning/)
  assert.doesNotMatch(styles, /transform 0\.25s var\(--hermes-spring-drag\)/)
  assert.match(styles, /\.cloud-node\.is-linked \.cloud-node-halo/)
})

test('GraphSpaceView makes the nebula the primary full-width graph entry', () => {
  const view = read('frontend/src/components/GraphSpaceView.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /class="cloud-inspector-card cloud-context-dock"/)
  assert.match(styles, /\.memory-cloud-layout\s*{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/)
  assert.match(styles, /\.cloud-constellation\s*{[\s\S]*min-height: 520px/)
  assert.match(styles, /\.cloud-inspector-card\.cloud-context-dock\s*{[\s\S]*grid-template-columns: minmax\(0, 1\.2fr\) minmax\(210px, 0\.8fr\) auto/)
  assert.match(styles, /\.cloud-inspector-card\.cloud-context-dock \.cloud-actions\s*{[\s\S]*grid-column: 3/)
  assert.match(styles, /@media \(max-width: 900px\)[\s\S]*\.cloud-inspector-card\.cloud-context-dock\s*{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/)
  assert.doesNotMatch(styles, /grid-template-columns: minmax\(0, 1\.35fr\) minmax\(260px, 0\.85fr\)/)
})

test('styles keep the graph overview header compact so the nebula reaches the first viewport', () => {
  const styles = read('frontend/src/styles.css')

  assert.match(styles, /\.graph-space-detail \.space-detail-head\s*{[\s\S]*padding-bottom: 12px/)
  assert.match(styles, /\.graph-space-detail \.space-detail-head h2\s*{[\s\S]*font-size: clamp\(1\.25rem, 2vw, 1\.65rem\)/)
  assert.match(styles, /\.graph-space-detail \.space-detail-head p\s*{[\s\S]*-webkit-line-clamp: 2/)
  assert.match(styles, /\.graph-space-detail \.space-detail-topbar\s*{[\s\S]*min-width: max-content/)
  assert.match(styles, /\.graph-space-detail \.graph-space-stats\s*{[\s\S]*flex-wrap: nowrap/)
  assert.match(styles, /\.graph-space-detail \.graph-stat-chip\s*{[\s\S]*white-space: nowrap/)
  assert.match(styles, /\.memory-cloud-head p\s*{[\s\S]*-webkit-line-clamp: 2/)
  assert.match(styles, /\.memory-cloud-console\s*{[\s\S]*padding: 14px/)
})

test('styles keep guided actions compact until phone width so the nebula stays visible early', () => {
  const styles = read('frontend/src/styles.css')
  const tabletStart = styles.indexOf('@media (max-width: 1020px)')
  const phoneStart = styles.indexOf('@media (max-width: 760px)')
  const tabletSection = styles.slice(tabletStart, phoneStart)
  const phoneSection = styles.slice(phoneStart)

  assert.doesNotMatch(tabletSection, /\.graph-guided-actions\s*{[\s\S]*grid-template-columns: 1fr/)
  assert.match(phoneSection, /\.graph-guided-actions\s*{[\s\S]*grid-template-columns: 1fr/)
})

test('App fetches saved questions and passes them into the graph cloud', () => {
  const app = read('frontend/src/App.vue')
  const spaces = read('frontend/src/components/SpacesView.vue')

  assert.match(app, /SavedQuestion/)
  assert.match(app, /const savedQuestions = ref<SavedQuestion\[\]>\(\[\]\)/)
  assert.match(app, /loadQuestions/)
  assert.match(app, /api<SavedQuestion\[\]>\('\/api\/questions'\)/)
  assert.match(app, /:questions="savedQuestions"/)
  assert.match(spaces, /questions: SavedQuestion\[\]/)
  assert.match(spaces, /:questions="questions"/)
})

test('App treats visualization as a knowledge-internal view instead of a duplicate nav item', () => {
  const app = read('frontend/src/App.vue')

  assert.match(app, /type ActiveView = 'recall' \| 'spaces' \| 'trust' \| 'collect'/)
  assert.match(app, /label: '知识库'/)
  assert.doesNotMatch(app, /label: '可视化'/)
  assert.doesNotMatch(app, /activeView === 'visualize'/)
  assert.doesNotMatch(app, /图谱可视化/)
})

test('App lets the knowledge overview route novice actions into collect and recall', () => {
  const app = read('frontend/src/App.vue')
  const spaces = read('frontend/src/components/SpacesView.vue')

  assert.match(app, /@start-collect="startCollect"/)
  assert.match(app, /function startCollect\(\)/)
  assert.match(app, /activeView\.value = 'collect'/)
  assert.match(spaces, /startCollect: \[\]/)
  assert.match(spaces, /\$emit\('startCollect'\)/)
})

test('App uses user-facing memory space names in the shell title', () => {
  const app = read('frontend/src/App.vue')

  assert.match(app, /function graphSpaceDisplayName/)
  assert.match(app, /if \(selectedSpaceId\.value === 'all'\) return '全部记忆'/)
  assert.match(app, /待整理/)
  assert.match(app, /主记忆/)
  assert.match(app, /graphSpaceDisplayName\(space\)/)
  assert.doesNotMatch(app, /全部图谱/)
  assert.doesNotMatch(app, /spaces\.value\.find\(.*\)\?\.name \|\| '图谱空间'/)
})

test('styles include phase 2B graph overview and mode switch classes', () => {
  const file = read('frontend/src/styles.css')

  assert.match(file, /\.memory-quick-actions/)
  assert.match(file, /\.memory-quick-action/)
  assert.match(file, /\.graph-space-card/)
  assert.match(file, /\.graph-space-stats/)
  assert.match(file, /\.graph-overview-mode/)
  assert.match(file, /\.graph-summary-card/)
  assert.match(file, /\.graph-mode-switch/)
  assert.match(file, /\.graph-workbench/)
  assert.match(file, /\.graph-stat-chip/)
  assert.match(file, /\.graph-recent-source-card/)
  assert.match(file, /\.graph-key-node-card/)
  assert.match(file, /\.open-loop-card/)
  assert.match(file, /\.graph-empty-inspector/)
  assert.match(file, /\.graph-guided-actions/)
  assert.match(file, /\.graph-guided-action/)
  assert.match(file, /\.space-question-starters/)
})

test('styles include the search-history memory cloud surface', () => {
  const file = read('frontend/src/styles.css')

  assert.match(file, /\.memory-cloud-console/)
  assert.match(file, /\.cloud-search-row/)
  assert.match(file, /\.cloud-orbit/)
  assert.match(file, /\.cloud-node/)
  assert.match(file, /\.cloud-node\.selected/)
  assert.match(file, /\.cloud-inspector-card/)
  assert.match(file, /\.cloud-evidence-list/)
  assert.match(file, /\.cloud-empty-state/)
})
