import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()

function read(relativePath: string) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('RecallHome uses the redesign ask card, receipts, and mode chips', () => {
  const file = read('frontend/src/components/RecallHome.vue')

  assert.match(file, /问过去 · ASK YOUR PAST SELF/)
  assert.match(file, /问问过去的你/)
  assert.match(file, /class="ask-card recall-command"/)
  assert.match(file, /class="ask-meta"/)
  assert.match(file, /全部材料/)
  assert.match(file, /只找文件/)
  assert.match(file, /只要回答/)
  assert.match(file, /快速/)
  assert.match(file, /深度 Thought/)
  assert.match(file, /桌上最近的回执/)
  assert.match(file, /普通聊天只给答案/)
  assert.match(file, /我们的价值是让用户找回自己说过的话/)
  assert.match(file, /displayQuestion \|\| '新对话'/)
  assert.match(file, /result-stream-status/)
  assert.match(file, /class="chat-top recall-chat-top"/)
  assert.match(file, /class="msg user"/)
  assert.match(file, /class="msg ai"/)
  assert.match(file, /class="composer-wrap recall-composer-wrap"/)
  assert.match(file, /问问过去的你，或一起接着想/)
  assert.match(file, /扮演过去的我/)
  assert.match(file, /props\.result\?\.local_files \|\| props\.focusGraph\?\.local_files/)
  assert.match(file, /:thought-history="thoughtHistory"/)
  assert.match(file, /emit\('recall', text, activeResultMode\.value, props\.depth\)/)
  assert.doesNotMatch(file, /recall-welcome-msg/)
})

test('RecallResult renders local files and answers as paper receipts', () => {
  const file = read('frontend/src/components/RecallResult.vue')

  assert.match(file, /recall-reference-result/)
  assert.match(file, /recall-file-receipts/)
  assert.match(file, /receipt-lg local-file-card local-file-compact-card/)
  assert.match(file, /打开原文/)
  assert.match(file, /openLocalFile/)
  assert.match(file, /snapgraph-thinking ai-aside/)
  assert.match(file, /AI 的补充 · 不冒充你/)
  assert.match(file, /RichMarkdown/)
  assert.match(file, /filterUserFacingAnswerMarkdown/)
  assert.match(file, /thinking-stream-state/)
  assert.match(file, /deeptutor-thought-card/)
  assert.match(file, /deeptutor-thought-header/)
  assert.match(file, /deeptutor-thought-box/)
  assert.match(file, /thoughtTraceItems/)
  assert.match(file, /thought-trace-label/)
  assert.match(file, /真实 Thought/)
  assert.match(file, /Solve mode/)
  assert.match(file, /currentThought/)
  assert.match(file, /thoughtLines/)
  assert.match(file, /thoughtNotice/)
  assert.match(file, /showCurrentThought = computed\(\(\) => depth\.value === 'deep' && Boolean\(currentThought\.value\)\)/)
  assert.match(file, /证据路径/)
  assert.match(file, /recall-memory-touchpoints/)
  assert.match(file, /AI 猜测/)
  assert.match(file, /why_saved_status/)
  assert.match(file, /AI-inferred/)
  assert.match(file, /本地没有找到文件/)
  assert.doesNotMatch(file, /写回预览/)
  assert.doesNotMatch(file, /需要确认的地方/)
  assert.doesNotMatch(file, /CoT/)
  assert.doesNotMatch(file, /chain-of-thought/i)
})

test('RecallResult keeps follow-up and local file events without old panels', () => {
  const result = read('frontend/src/components/RecallResult.vue')
  const home = read('frontend/src/components/RecallHome.vue')

  assert.match(result, /defineEmits/)
  assert.match(result, /askFollowUp: \[question: string\]/)
  assert.match(result, /openLocalFile: \[file: LocalFileResult\]/)
  assert.match(result, /emit\('openLocalFile'/)
  assert.doesNotMatch(result, /RecallReflectionPanel/)

  assert.match(home, /@ask-follow-up="askFollowUp"/)
  assert.match(home, /@open-local-file="\$emit\('openLocalFile', \$event\)"/)
  assert.match(home, /function askFollowUp\(questionText: string\)/)
})

test('Recall response types include local files, modes, depth, and Thought', () => {
  const result = read('frontend/src/components/RecallResult.vue')
  const types = read('frontend/src/types.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /export type RecallProjection/)
  assert.match(types, /recall_projection\?: RecallProjection/)
  assert.match(types, /export type LocalFileResult/)
  assert.match(types, /raw_path: string/)
  assert.match(types, /open_target: 'raw' \| 'source_page'/)
  assert.match(types, /FocusGraph[\s\S]*local_files\?: LocalFileResult\[\]/)
  assert.match(types, /local_files\?: LocalFileResult\[\]/)
  assert.match(types, /export type RecallMode = 'auto' \| 'files' \| 'answer'/)
  assert.match(types, /export type RecallDepth = 'quick' \| 'deep'/)
  assert.match(types, /export type RecallThought/)
  assert.match(types, /thought\?: RecallThought/)
  assert.match(types, /export type ThoughtHistoryPayload/)
  assert.match(result, /const projection = computed/)
  assert.match(result, /<RichMarkdown :markdown="displayAnswerMarkdown" \/>/)
  assert.match(styles, /\.recall-reference-result/)
  assert.match(styles, /\.local-file-card/)
  assert.match(styles, /\.local-file-compact-card/)
  assert.match(styles, /\.result-stream-status/)
  assert.match(styles, /\.rich-markdown/)
  assert.match(styles, /\.rich-mermaid/)
  assert.match(styles, /\.math-block/)
  assert.match(styles, /\.thinking-stream-state/)
  assert.match(styles, /\.thinking-footnotes/)
  assert.match(styles, /\.recall-memory-touchpoints/)
  assert.match(styles, /\.deeptutor-thought-card/)
})

test('App preserves upload batch ids and scopes recall requests', () => {
  const file = read('frontend/src/App.vue')

  assert.match(file, /recentBatchSourceIds/)
  assert.match(file, /uploadedSourceIds/)
  assert.match(file, /context_source_ids/)
  assert.match(file, /askRecentBatch/)
  assert.match(file, /@ask-batch="askRecentBatch"/)
  assert.match(file, /currentRecallSpaceId/)
  assert.match(file, /function recallSpaceScope\(\)/)
  assert.match(file, /space_id: recallSpaceScope\(\)/)
  assert.doesNotMatch(file, /space_id: 'all'/)
  assert.match(file, /\/api\/focus[\s\S]*context_source_ids/)
  assert.match(file, /\/api\/ask\/stream[\s\S]*context_source_ids/)
  assert.match(file, /selectedRecallMode/)
  assert.match(file, /currentRecallMode/)
  assert.match(file, /selectedRecallDepth/)
  assert.match(file, /thoughtHistory/)
  assert.match(file, /loadThoughtHistory/)
  assert.match(file, /currentThought/)
  assert.match(file, /event === 'thought'/)
  assert.match(file, /api<ThoughtHistoryPayload>\('\/api\/thought-history\?limit=4'\)/)
  assert.match(file, /mode !== 'answer'/)
  assert.match(file, /mode === 'files'/)
})

test('CollectView exposes a batch receipt and direct follow-up action', () => {
  const file = read('frontend/src/components/CollectView.vue')

  assert.match(file, /batchReceiptVisible/)
  assert.match(file, /本批次回执/)
  assert.match(file, /追问这批材料/)
  assert.match(file, /askBatch/)
  assert.match(file, /emit\('askBatch'/)
  assert.match(file, /batch-source-list/)
})
