import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()

function read(relativePath: string) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('RecallHome mirrors the StudyAgent empty chat surface and example chips', () => {
  const file = read('frontend/src/components/RecallHome.vue')

  assert.match(file, /找回当时为什么在意它/)
  assert.match(file, /displayQuestion \|\| '新对话'/)
  assert.doesNotMatch(file, /今天想学什么？/)
  assert.doesNotMatch(file, /把这个概念讲给初学者听，再给一个判断例子。/)
  assert.match(file, /我为什么要从 LLM Wiki 开始/)
  assert.match(file, /这批材料里/)
  assert.match(file, /哪些内容只是 AI 推断/)
  assert.match(file, /还有哪些 open loop/)
  assert.match(file, /先回到本地文件/)
  assert.match(file, /本地文件和保存理由/)
  assert.doesNotMatch(file, /图谱路径/)
  assert.match(file, /recall-command/)
  assert.match(file, /example-chip/)
  assert.match(file, /placeholder="例如：我之前为什么觉得这个方向值得做？"/)
  assert.match(file, /v-if="!showResult" class="starter-grid"/)
  assert.match(file, /@open-local-file="\$emit\('openLocalFile', \$event\)"/)
  assert.match(file, /question\.value = prompt/)
  assert.match(file, /'is-answering': busy/)
  assert.match(file, /result-stream-status/)
  assert.match(file, /recall-mode-switch/)
  assert.match(file, /modeOptions/)
  assert.match(file, /'auto' as const/)
  assert.match(file, /'files' as const/)
  assert.match(file, /'answer' as const/)
  assert.match(file, /modeChanged/)
  assert.match(file, /props\.result\?\.local_files \|\| props\.focusGraph\?\.local_files/)
})

test('RecallResult defaults to clickable local files and bounded SnapGraph thinking', () => {
  const file = read('frontend/src/components/RecallResult.vue')

  assert.match(file, /recall-response-focus/)
  assert.match(file, /local-file-results/)
  assert.match(file, /召回的本地文件/)
  assert.match(file, /openLocalFile/)
  assert.match(file, /打开/)
  assert.match(file, /snapgraph-thinking/)
  assert.match(file, /SnapGraph 的思考/)
  assert.match(file, /RichMarkdown/)
  assert.match(file, /answerMarkdown/)
  assert.match(file, /recall-response-stack/)
  assert.match(file, /local-file-compact-card/)
  assert.match(file, /thinking-stream-state/)
  assert.match(file, /thinkingStateLabel/)
  assert.match(file, /thinking-footnotes/)
  assert.match(file, /依据/)
  assert.match(file, /AI 推断/)
  assert.match(file, /why_saved_status/)
  assert.match(file, /AI-inferred/)
  assert.match(file, /isResolvingLocalFiles/)
  assert.match(file, /查找中/)
  assert.doesNotMatch(file, /无文件/)
  assert.doesNotMatch(file, /写回预览/)
  assert.doesNotMatch(file, /需要确认的地方/)
})

test('RecallResult keeps follow-up actions without exposing the old reflection panel', () => {
  const result = read('frontend/src/components/RecallResult.vue')
  const home = read('frontend/src/components/RecallHome.vue')

  assert.match(result, /defineEmits/)
  assert.match(result, /askFollowUp: \[question: string\]/)
  assert.match(result, /openLocalFile: \[file: LocalFileResult\]/)
  assert.match(result, /function askAboutFile/)
  assert.match(result, /emit\('askFollowUp'/)
  assert.match(result, /emit\('openLocalFile'/)
  assert.doesNotMatch(result, /RecallReflectionPanel/)

  assert.match(home, /@ask-follow-up="askFollowUp"/)
  assert.match(home, /@open-local-file="\$emit\('openLocalFile', \$event\)"/)
  assert.match(home, /function askFollowUp\(questionText: string\)/)
  assert.match(home, /emit\('recall', text, activeResultMode\.value\)/)
})

test('Recall response types include local file results while preserving projection data', () => {
  const result = read('frontend/src/components/RecallResult.vue')
  const types = read('frontend/src/types.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /export type RecallProjection/)
  assert.match(types, /recall_projection\?: RecallProjection/)
  assert.match(types, /export type LocalFileResult/)
  assert.match(types, /raw_path: string/)
  assert.match(types, /open_target: 'raw' \| 'source_page'/)
  assert.match(types, /FocusGraph[\s\S]*local_files\?: LocalFileResult\[\]/)
  assert.match(types, /local_files\?: LocalFileResult\[\]/)
  assert.match(types, /export type RecallMode = 'auto' \| 'files' \| 'answer'/)
  assert.match(types, /type RecallEvidenceKind = 'user_anchor' \| 'source' \| 'ai_inference' \| 'graph_path'/)

  assert.match(result, /const projection = computed/)
  assert.match(result, /<RichMarkdown :markdown="displayAnswerMarkdown" \/>/)
  assert.match(result, /filterUserFacingAnswerMarkdown/)
  assert.doesNotMatch(result, /compactText/)
  assert.match(styles, /\.recall-response-focus/)
  assert.match(styles, /\.recall-response-stack/)
  assert.match(styles, /\.local-file-card/)
  assert.match(styles, /\.local-file-compact-card/)
  assert.match(styles, /\.local-file-loading/)
  assert.match(styles, /\.result-stream-status/)
  assert.match(styles, /\.rich-markdown/)
  assert.match(styles, /\.rich-mermaid/)
  assert.match(styles, /\.math-block/)
  assert.match(styles, /\.thinking-stream-state/)
  assert.match(styles, /\.thinking-footnotes/)
})

test('App preserves recent upload batch ids and scopes recall requests to the current space', () => {
  const file = read('frontend/src/App.vue')

  assert.match(file, /recentBatchSourceIds/)
  assert.match(file, /uploadedSourceIds/)
  assert.match(file, /context_source_ids/)
  assert.match(file, /askRecentBatch/)
  assert.match(file, /@ask-batch="askRecentBatch"/)
  assert.match(file, /currentRecallSpaceId/)
  assert.match(file, /function recallSpaceScope\(\)/)
  assert.match(file, /space_id: recallSpaceScope\(\)/)
  assert.doesNotMatch(file, /space_id: 'all'/)
  assert.match(file, /\/api\/focus[\s\S]*context_source_ids/)
  assert.match(file, /\/api\/ask\/stream[\s\S]*context_source_ids/)
  assert.match(file, /selectedRecallMode/)
  assert.match(file, /currentRecallMode/)
  assert.match(file, /mode !== 'answer'/)
  assert.match(file, /mode === 'files'/)
})

test('CollectView exposes a batch receipt and direct follow-up action', () => {
  const file = read('frontend/src/components/CollectView.vue')

  assert.match(file, /batchReceiptVisible/)
  assert.match(file, /本批次/)
  assert.match(file, /追问这批材料/)
  assert.match(file, /askBatch/)
  assert.match(file, /emit\('askBatch'/)
  assert.match(file, /batch-question-button/)
})

test('styles include focused recall result mode and mobile-safe rows', () => {
  const file = read('frontend/src/styles.css')

  assert.match(file, /\.recall-command/)
  assert.match(file, /\.recall-response-focus/)
  assert.match(file, /\.local-file-results/)
  assert.match(file, /\.snapgraph-thinking/)
  assert.match(file, /\.focus-panel-head/)
  assert.match(file, /\.local-file-card/)
  assert.match(file, /\.local-file-compact-card/)
  assert.match(file, /\.local-file-actions/)
  assert.match(file, /\.thinking-block/)
  assert.match(file, /\.focus-empty-state/)
  assert.match(file, /\.recall-mode-switch/)
  assert.match(file, /\.recent-question-chip/)
  assert.match(file, /\.source-link-button/)
  assert.match(file, /\.recall-home\.has-result \.recall-command textarea/)
  assert.match(file, /--snap-title/)
  assert.doesNotMatch(file, /Kaiti SC/)
  assert.match(file, /\.batch-receipt-strip/)
  assert.match(file, /\.batch-source-list/)
  assert.match(file, /\.batch-question-button/)
})
