import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()

function read(relativePath: string) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('App adopts the redesign reference shell and four user-facing entries', () => {
  const file = read('frontend/src/App.vue')

  assert.match(file, /class="app study-shell snapgraph-reference-shell"/)
  assert.match(file, /class="side study-sidebar"/)
  assert.match(file, /class="main study-chat-shell"/)
  assert.match(file, /type ActiveView = 'recall' \| 'emerge' \| 'collect' \| 'shelf'/)
  assert.match(file, /label: '问过去'/)
  assert.match(file, /label: '涌现'/)
  assert.match(file, /label: '收下'/)
  assert.match(file, /label: '书架'/)
  assert.match(file, /seal: '问'/)
  assert.match(file, /seal: '涌'/)
  assert.match(file, /seal: '收'/)
  assert.match(file, /seal: '架'/)
  assert.match(file, /<RecallHome/)
  assert.match(file, /<OrganizeView/)
  assert.match(file, /<CollectView/)
  assert.match(file, /<ShelfView/)
  assert.match(file, /snapgraph\.recallThreads/)
  assert.match(file, /rememberRecallThread/)
  assert.match(file, /loadRecallThreads/)
  assert.doesNotMatch(file, /class="rail activity-panel"/)
  assert.doesNotMatch(file, /session-title-button/)
  assert.doesNotMatch(file, /sidebar-new-chat/)
  assert.doesNotMatch(file, /label: '知识库'/)
  assert.doesNotMatch(file, /label: '信任'/)
})

test('RecallHome mirrors the redesign ask desk instead of old chat welcome', () => {
  const file = read('frontend/src/components/RecallHome.vue')

  assert.match(file, /问过去 · ASK YOUR PAST SELF/)
  assert.match(file, /问问过去的你/)
  assert.match(file, /ask-card recall-command/)
  assert.match(file, /class="ask-row"/)
  assert.match(file, /class="ask-input"/)
  assert.match(file, /找　回/)
  assert.match(file, /桌上最近的回执/)
  assert.match(file, /class="receipts"/)
  assert.match(file, /class="receipt"/)
  assert.match(file, /class="thread recall-thread stream"/)
  assert.match(file, /class="chat-top recall-chat-top"/)
  assert.match(file, /class="msg user"/)
  assert.match(file, /class="u-bubble q-bubble"/)
  assert.match(file, /class="msg ai"/)
  assert.match(file, /class="composer-wrap recall-composer-wrap"/)
  assert.match(file, /class="composer recall-command"/)
  assert.match(file, /class="c-send"/)
  assert.match(file, /q-bubble/)
  assert.match(file, /displayQuestion \|\| '新对话'/)
  assert.match(file, /深度 Thought/)
  assert.match(file, /'auto' as const/)
  assert.match(file, /'files' as const/)
  assert.match(file, /'answer' as const/)
  assert.match(file, /@open-local-file="\$emit\('openLocalFile', \$event\)"/)
  assert.doesNotMatch(file, /recall-welcome-msg/)
  assert.doesNotMatch(file, /class="rail/)
})

test('styles include the exact paper reference shell and card motion vocabulary', () => {
  const file = read('frontend/src/styles.css')

  assert.match(file, /--paper-bg: #f1ecdf;/)
  assert.match(file, /--paper-card: #fcfaf3;/)
  assert.match(file, /--paper-ink: #1b1c20;/)
  assert.match(file, /--paper-gold: #a8853b;/)
  assert.match(file, /--paper-moss: #5f7050;/)
  assert.match(file, /--paper-rust: #a8493d;/)
  assert.match(file, /fonts\.googleapis\.com\/css2\?family=Noto\+Serif\+SC/)
  assert.match(file, /\.snapgraph-reference-shell \.side[\s\S]*width: 238px/)
  assert.match(file, /\.snapgraph-reference-shell \.main[\s\S]*padding: 56px 56px 100px/)
  assert.match(file, /\.snapgraph-reference-shell \.view[\s\S]*max-width: 850px/)
  assert.match(file, /\.snapgraph-reference-shell \.wordmark[\s\S]*font-family: "Cormorant Garamond"/)
  assert.match(file, /\.snapgraph-reference-shell \.receipt:hover[\s\S]*translateY\(-5px\)/)
  assert.match(file, /\.snapgraph-reference-shell \.main\.is-recall-chat/)
  assert.match(file, /\.snapgraph-reference-shell \.recall-home\.has-result[\s\S]*height: 100%/)
  assert.match(file, /\.snapgraph-reference-shell \.recall-chat-top/)
  assert.match(file, /\.snapgraph-reference-shell \.recall-composer-wrap/)
  assert.match(file, /\.snapgraph-reference-shell \.claim-card\.exit-l/)
  assert.match(file, /\.snapgraph-reference-shell \.claim-card\.exit-r/)
  assert.match(file, /fractalNoise/)
  assert.match(file, /gpulse/)
  assert.match(file, /dot-breathe/)
})

test('mobile redesign shell collapses to the reference compact top nav', () => {
  const file = read('frontend/src/styles.css')

  assert.match(file, /@media \(max-width: 960px\)[\s\S]*\.snapgraph-reference-shell\.app\s*{[\s\S]*flex-direction: column/)
  assert.match(file, /@media \(max-width: 960px\)[\s\S]*\.snapgraph-reference-shell \.side\s*{[\s\S]*flex-direction: row/)
  assert.match(file, /@media \(max-width: 960px\)[\s\S]*\.snapgraph-reference-shell \.nav\s*{[\s\S]*flex-direction: row/)
  assert.match(file, /@media \(max-width: 960px\)[\s\S]*\.snapgraph-reference-shell \.receipts\s*{[\s\S]*overflow-x: auto/)
  assert.match(file, /@media \(max-width: 960px\)[\s\S]*\.snapgraph-reference-shell \.receipt\s*{[\s\S]*flex: 0 0 min\(280px, 78vw\)/)
  assert.match(file, /@media \(max-width: 960px\)[\s\S]*\.snapgraph-reference-shell \.collect-grid\s*{[\s\S]*grid-template-columns: 1fr/)
  assert.match(file, /@media \(max-width: 960px\)[\s\S]*\.snapgraph-reference-shell \.shelf-grid\s*{[\s\S]*grid-template-columns: 1fr/)
})
