import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()

function read(relativePath: string) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('App exposes Trust Center as a primary workspace view', () => {
  const app = read('frontend/src/App.vue')

  assert.match(app, /type ActiveView = 'recall' \| 'spaces' \| 'trust' \| 'collect'/)
  assert.match(app, /label: '信任'/)
  assert.match(app, /ShieldCheck/)
  assert.match(app, /<TrustCenterView/)
  assert.match(app, /loadTrustCenter/)
  assert.match(app, /applyTrustBatch/)
  assert.match(app, /updateTrustOpenLoop/)
  assert.match(app, /\/api\/trust\/review/)
  assert.match(app, /\/api\/trust\/open-loops/)
  assert.match(app, /\/api\/trust\/diagnostics/)
})

test('Trust Center components expose review operations, evidence, open loops, and diagnostics', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const batch = read('frontend/src/components/TrustBatchActionBar.vue')
  const loops = read('frontend/src/components/TrustOpenLoopPanel.vue')
  const diagnostics = read('frontend/src/components/TrustDiagnosticsPanel.vue')
  const types = read('frontend/src/components/trustCenterTypes.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /TrustRiskLevel/)
  assert.match(types, /TrustReviewStatus/)
  assert.match(types, /TrustOpenLoopState/)
  assert.match(types, /TrustBatchPayload/)
  assert.match(view, /trust-center-view/)
  assert.match(view, /TrustReviewInbox/)
  assert.match(view, /TrustReviewDetail/)
  assert.match(view, /TrustBatchActionBar/)
  assert.match(view, /TrustOpenLoopPanel/)
  assert.match(view, /TrustDiagnosticsPanel/)
  assert.match(inbox, /risk_level/)
  assert.match(inbox, /selectedSourceIds/)
  assert.match(inbox, /filterChanged/)
  assert.match(detail, /evidence_paths/)
  assert.match(detail, /history/)
  assert.match(detail, /batchAction/)
  assert.match(batch, /batchAction/)
  assert.match(batch, /confirmed/)
  assert.match(batch, /deferred/)
  assert.match(loops, /open-loop/)
  assert.match(loops, /resolved/)
  assert.match(loops, /dismissed/)
  assert.match(diagnostics, /queue_total/)
  assert.match(diagnostics, /ai_inferred_unreviewed/)
  assert.match(styles, /\.trust-center-view/)
  assert.match(styles, /\.trust-summary-grid/)
  assert.match(styles, /\.trust-review-inbox/)
  assert.match(styles, /\.trust-detail-panel/)
  assert.match(styles, /\.trust-batch-bar/)
  assert.match(styles, /\.trust-open-loop-panel/)
  assert.match(styles, /\.trust-diagnostics-panel/)
  assert.match(styles, /\.trust-filter-row\s*{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(140px, 1fr\)\)/)
  assert.match(styles, /\.trust-filter-row input\s*{[\s\S]*grid-column: 1 \/ -1/)
  assert.match(styles, /\.trust-filter-row \.ghost-button\s*{[\s\S]*white-space: nowrap/)
})

test('Trust Center reduces information pressure with compact focus and progressive disclosure', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const diagnostics = read('frontend/src/components/TrustDiagnosticsPanel.vue')
  const loops = read('frontend/src/components/TrustOpenLoopPanel.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /trust-focus-strip/)
  assert.match(view, /trust-focus-primary/)
  assert.match(view, /focusHeadline/)
  assert.match(view, /trust-focus-stats/)
  assert.match(view, /compactMetrics/)
  assert.match(inbox, /trust-review-micro-meta/)
  assert.doesNotMatch(inbox, /trust-review-action-hint/)
  assert.match(detail, /trust-detail-brief/)
  assert.match(detail, /trust-detail-disclosure/)
  assert.match(detail, /<details/)
  assert.match(diagnostics, /trust-diagnostics-summary/)
  assert.match(diagnostics, /<details/)
  assert.match(loops, /visibleLoops/)
  assert.match(loops, /trust-loop-overflow-note/)
  assert.match(styles, /\.trust-focus-strip/)
  assert.match(styles, /\.trust-detail-disclosure/)
  assert.match(styles, /\.trust-review-micro-meta/)
  assert.match(styles, /\.trust-diagnostics-summary/)
})

test('Trust Center reads like a simple Chinese knowledge workflow by default', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const report = read('frontend/src/components/TrustQuietReport.vue')
  const digest = read('frontend/src/components/TrustAnalysisDigest.vue')
  const lens = read('frontend/src/components/TrustRiskLens.vue')
  const coach = read('frontend/src/components/TrustDecisionCoach.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /信任检查/)
  assert.match(view, /这里只帮你确认一件事/)
  assert.match(view, /trust-home-actions/)
  assert.match(view, /先确认 AI 猜测/)
  assert.match(view, /处理未闭环问题/)
  assert.match(view, /高级检查/)
  assert.match(inbox, /需要你确认的材料/)
  assert.match(detail, /当前材料/)
  assert.match(report, /信任概览/)
  assert.match(digest, /系统简短判断/)
  assert.match(lens, /为什么需要你看/)
  assert.match(coach, /你的判断/)
  assert.match(styles, /\.trust-home-actions/)
  assert.match(styles, /\.trust-advanced-review/)
  assert.doesNotMatch(view, /Trust Operations|Review Session|Trust report/)
  assert.doesNotMatch(detail, /Evidence Detail/)
  assert.doesNotMatch(report, /Trust report|Report detail|sections<\/strong>/)
  assert.doesNotMatch(digest, /Compressed analysis|Decision impact|Evidence compression|hidden details/)
  assert.doesNotMatch(lens, /Risk Lens/)
  assert.doesNotMatch(coach, /Decision Coach/)
})

test('Trust Center keeps the default review screen dense and mostly above the fold', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const coach = read('frontend/src/components/TrustDecisionCoach.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /trust-how-it-works/)
  assert.match(view, /<details class="trust-how-it-works">/)
  assert.match(inbox, /trust-review-micro-meta/)
  assert.match(inbox, /const compactReasonLimit = 64/)
  assert.doesNotMatch(inbox, /TrustReviewSignals/)
  assert.doesNotMatch(inbox, /trust-review-action-hint/)
  assert.match(detail, /trust-detail-compact-disclosures/)
  assert.match(detail, /<TrustDecisionCoach/)
  assert.match(detail, /<TrustRiskLens/)
  assert.match(detail, /<TrustAnalysisDigest/)
  assert.match(coach, /trust-decision-current-help/)
  assert.match(coach, /trust-decision-note-drawer/)
  assert.match(coach, /needsDraftDetails/)
  assert.doesNotMatch(coach, /decisionActionDescription\(option.action\)/)
  assert.match(styles, /\.trust-workbench-grid\s*{[\s\S]*max-height: calc\(100vh - 250px\)/)
  assert.match(styles, /\.trust-review-card\s*{[\s\S]*padding: 8px 10px/)
  assert.match(styles, /\.trust-detail-compact-disclosures/)
  assert.match(styles, /\.trust-decision-note-drawer/)
  assert.match(styles, /\.trust-decision-options\s*{[\s\S]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
})

test('Trust Center quick actions expose selected feedback and do not trap page scrolling', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /quickActionClass\('high-risk'\)/)
  assert.match(view, /quickActionClass\('open-loops'\)/)
  assert.match(view, /quickActionClass\('all'\)/)
  assert.match(view, /trust-quick-action-state/)
  assert.match(view, /aria-pressed="selectedSessionMode === 'open-loops'"/)
  assert.match(view, /aria-pressed="selectedSessionMode === 'all'"/)
  assert.match(view, /trustSessionModeLabel/)
  assert.match(styles, /\.trust-home-actions \.memory-quick-action\.active/)
  assert.match(styles, /\.trust-quick-action-state/)
  assert.doesNotMatch(styles, /\.trust-home-actions \.memory-quick-action\.active::after/)
  assert.match(styles, /\.trust-review-inbox,\s*\n\.trust-detail-panel\s*{[\s\S]*overscroll-behavior: auto/)
  assert.match(styles, /@media \(max-width: 980px\)[\s\S]*\.trust-workbench-grid\s*{[\s\S]*max-height: none/)
  assert.match(styles, /@media \(max-width: 980px\)[\s\S]*\.trust-review-inbox,\s*\n\s*\.trust-detail-panel\s*{[\s\S]*overflow-y: visible/)
})

test('Trust Center defines session types and shared decision copy helpers', () => {
  const types = read('frontend/src/components/trustCenterTypes.ts')
  const copy = read('frontend/src/components/trustCenterCopy.ts')

  assert.match(types, /TrustReviewSessionMode/)
  assert.match(types, /TrustDecisionOption/)
  assert.match(types, /TrustReviewFocus/)
  assert.match(types, /TrustSignals/)
  assert.match(copy, /riskToneLabel/)
  assert.match(copy, /boundaryLabel/)
  assert.match(copy, /reviewStatusLabel/)
  assert.match(copy, /decisionActionLabel/)
  assert.match(copy, /sessionModeLabel/)
  assert.match(copy, /sessionModeDescription/)
  assert.match(copy, /confidenceLabel/)
})

test('Trust Center adds a guided review session planner and progress strip', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const planner = read('frontend/src/components/TrustSessionPlanner.vue')
  const progress = read('frontend/src/components/TrustReviewProgress.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /TrustSessionPlanner/)
  assert.match(view, /TrustReviewProgress/)
  assert.match(view, /TrustReviewSessionMode/)
  assert.match(view, /selectedSessionMode/)
  assert.match(view, /sessionItems/)
  assert.match(planner, /trust-session-planner/)
  assert.match(planner, /sessionModeLabel/)
  assert.match(planner, /sessionModeDescription/)
  assert.match(progress, /trust-review-progress/)
  assert.match(progress, /selectedCount/)
  assert.match(progress, /nextStep/)
  assert.match(styles, /\.trust-session-planner/)
  assert.match(styles, /\.trust-review-progress/)
  assert.match(styles, /\.trust-session-modes/)
})

test('Trust Center adds reusable signals, risk lens, and decision coach', () => {
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const signals = read('frontend/src/components/TrustReviewSignals.vue')
  const lens = read('frontend/src/components/TrustRiskLens.vue')
  const coach = read('frontend/src/components/TrustDecisionCoach.vue')
  const styles = read('frontend/src/styles.css')

  assert.doesNotMatch(inbox, /TrustReviewSignals/)
  assert.doesNotMatch(detail, /TrustReviewSignals/)
  assert.match(detail, /TrustRiskLens/)
  assert.match(detail, /TrustDecisionCoach/)
  assert.match(signals, /trust-review-signals/)
  assert.match(signals, /confidenceLabel/)
  assert.match(lens, /trust-risk-lens/)
  assert.match(lens, /riskReasons/)
  assert.match(coach, /trust-decision-coach/)
  assert.match(coach, /submitRewrite/)
  assert.match(coach, /validationMessage/)
  assert.match(styles, /\.trust-review-signals/)
  assert.match(styles, /\.trust-risk-lens/)
  assert.match(styles, /\.trust-decision-coach/)
})

test('Trust Center secondary panels include guidance and responsive session layout', () => {
  const batch = read('frontend/src/components/TrustBatchActionBar.vue')
  const loops = read('frontend/src/components/TrustOpenLoopPanel.vue')
  const diagnostics = read('frontend/src/components/TrustDiagnosticsPanel.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(batch, /trust-batch-guidance/)
  assert.match(batch, /batchGuidance/)
  assert.match(loops, /trust-loop-priority-note/)
  assert.match(loops, /priorityNote/)
  assert.match(diagnostics, /trust-diagnostics-guidance/)
  assert.match(diagnostics, /diagnosticsGuidance/)
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.trust-session-planner/)
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.trust-decision-options/)
  assert.match(styles, /\.trust-batch-guidance/)
  assert.match(styles, /\.trust-loop-priority-note/)
  assert.match(styles, /\.trust-diagnostics-guidance/)
})

test('Trust Center exposes engine 3 analysis without adding visual pressure', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const report = read('frontend/src/components/TrustQuietReport.vue')
  const digest = read('frontend/src/components/TrustAnalysisDigest.vue')
  const types = read('frontend/src/components/trustCenterTypes.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /TrustEngineAnalysis/)
  assert.match(types, /TrustSessionPayload/)
  assert.match(types, /TrustReportPayload/)
  assert.match(view, /TrustQuietReport/)
  assert.match(detail, /TrustAnalysisDigest/)
  assert.match(report, /trust-quiet-report/)
  assert.match(report, /<details/)
  assert.match(digest, /trust-analysis-digest/)
  assert.match(digest, /evidence_compression/)
  assert.match(styles, /\.trust-quiet-report/)
  assert.match(styles, /\.trust-analysis-digest/)
})
