import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()

function read(relativePath: string) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('App exposes Trust Center as a primary workspace view', () => {
  const app = read('frontend/src/App.vue')

  assert.match(app, /type ActiveView = 'recall' \| 'spaces' \| 'trust' \| 'collect'/)
  assert.match(app, /label: '信任'/)
  assert.match(app, /ShieldCheck/)
  assert.match(app, /<TrustCenterView/)
  assert.match(app, /loadTrustCenter/)
  assert.match(app, /applyTrustBatch/)
  assert.match(app, /updateTrustOpenLoop/)
  assert.match(app, /\/api\/trust\/review/)
  assert.match(app, /\/api\/trust\/open-loops/)
  assert.match(app, /\/api\/trust\/diagnostics/)
})

test('Trust Center components expose review operations, evidence, open loops, and diagnostics', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const batch = read('frontend/src/components/TrustBatchActionBar.vue')
  const loops = read('frontend/src/components/TrustOpenLoopPanel.vue')
  const diagnostics = read('frontend/src/components/TrustDiagnosticsPanel.vue')
  const types = read('frontend/src/components/trustCenterTypes.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /TrustRiskLevel/)
  assert.match(types, /TrustReviewStatus/)
  assert.match(types, /TrustOpenLoopState/)
  assert.match(types, /TrustBatchPayload/)
  assert.match(view, /trust-center-view/)
  assert.match(view, /TrustReviewInbox/)
  assert.match(view, /TrustReviewDetail/)
  assert.match(view, /TrustBatchActionBar/)
  assert.match(view, /TrustOpenLoopPanel/)
  assert.match(view, /TrustDiagnosticsPanel/)
  assert.match(inbox, /risk_level/)
  assert.match(inbox, /selectedSourceIds/)
  assert.match(inbox, /filterChanged/)
  assert.match(detail, /evidence_paths/)
  assert.match(detail, /history/)
  assert.match(detail, /batchAction/)
  assert.match(batch, /batchAction/)
  assert.match(batch, /confirmed/)
  assert.match(batch, /deferred/)
  assert.match(loops, /open-loop/)
  assert.match(loops, /resolved/)
  assert.match(loops, /dismissed/)
  assert.match(diagnostics, /queue_total/)
  assert.match(diagnostics, /ai_inferred_unreviewed/)
  assert.match(styles, /\.trust-center-view/)
  assert.match(styles, /\.trust-summary-grid/)
  assert.match(styles, /\.trust-review-inbox/)
  assert.match(styles, /\.trust-detail-panel/)
  assert.match(styles, /\.trust-batch-bar/)
  assert.match(styles, /\.trust-open-loop-panel/)
  assert.match(styles, /\.trust-diagnostics-panel/)
  assert.match(styles, /\.trust-filter-row\s*{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(140px, 1fr\)\)/)
  assert.match(styles, /\.trust-filter-row input\s*{[\s\S]*grid-column: 1 \/ -1/)
  assert.match(styles, /\.trust-filter-row \.ghost-button\s*{[\s\S]*white-space: nowrap/)
})

test('Trust Center reduces information pressure with compact focus and progressive disclosure', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const diagnostics = read('frontend/src/components/TrustDiagnosticsPanel.vue')
  const loops = read('frontend/src/components/TrustOpenLoopPanel.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /trust-focus-strip/)
  assert.match(view, /trust-focus-primary/)
  assert.match(view, /focusHeadline/)
  assert.match(view, /trust-focus-stats/)
  assert.match(view, /compactMetrics/)
  assert.match(inbox, /trust-review-compact-meta/)
  assert.match(inbox, /trust-review-action-hint/)
  assert.match(detail, /trust-detail-brief/)
  assert.match(detail, /trust-detail-disclosure/)
  assert.match(detail, /<details/)
  assert.match(diagnostics, /trust-diagnostics-summary/)
  assert.match(diagnostics, /<details/)
  assert.match(loops, /visibleLoops/)
  assert.match(loops, /trust-loop-overflow-note/)
  assert.match(styles, /\.trust-focus-strip/)
  assert.match(styles, /\.trust-detail-disclosure/)
  assert.match(styles, /\.trust-review-compact-meta/)
  assert.match(styles, /\.trust-diagnostics-summary/)
})

test('Trust Center defines session types and shared decision copy helpers', () => {
  const types = read('frontend/src/components/trustCenterTypes.ts')
  const copy = read('frontend/src/components/trustCenterCopy.ts')

  assert.match(types, /TrustReviewSessionMode/)
  assert.match(types, /TrustDecisionOption/)
  assert.match(types, /TrustReviewFocus/)
  assert.match(types, /TrustSignals/)
  assert.match(copy, /riskToneLabel/)
  assert.match(copy, /boundaryLabel/)
  assert.match(copy, /reviewStatusLabel/)
  assert.match(copy, /decisionActionLabel/)
  assert.match(copy, /sessionModeLabel/)
  assert.match(copy, /sessionModeDescription/)
  assert.match(copy, /confidenceLabel/)
})

test('Trust Center adds a guided review session planner and progress strip', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const planner = read('frontend/src/components/TrustSessionPlanner.vue')
  const progress = read('frontend/src/components/TrustReviewProgress.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(view, /TrustSessionPlanner/)
  assert.match(view, /TrustReviewProgress/)
  assert.match(view, /TrustReviewSessionMode/)
  assert.match(view, /selectedSessionMode/)
  assert.match(view, /sessionItems/)
  assert.match(planner, /trust-session-planner/)
  assert.match(planner, /sessionModeLabel/)
  assert.match(planner, /sessionModeDescription/)
  assert.match(progress, /trust-review-progress/)
  assert.match(progress, /selectedCount/)
  assert.match(progress, /nextStep/)
  assert.match(styles, /\.trust-session-planner/)
  assert.match(styles, /\.trust-review-progress/)
  assert.match(styles, /\.trust-session-modes/)
})

test('Trust Center adds reusable signals, risk lens, and decision coach', () => {
  const inbox = read('frontend/src/components/TrustReviewInbox.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const signals = read('frontend/src/components/TrustReviewSignals.vue')
  const lens = read('frontend/src/components/TrustRiskLens.vue')
  const coach = read('frontend/src/components/TrustDecisionCoach.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(inbox, /TrustReviewSignals/)
  assert.match(detail, /TrustReviewSignals/)
  assert.match(detail, /TrustRiskLens/)
  assert.match(detail, /TrustDecisionCoach/)
  assert.match(signals, /trust-review-signals/)
  assert.match(signals, /confidenceLabel/)
  assert.match(lens, /trust-risk-lens/)
  assert.match(lens, /riskReasons/)
  assert.match(coach, /trust-decision-coach/)
  assert.match(coach, /submitRewrite/)
  assert.match(coach, /validationMessage/)
  assert.match(styles, /\.trust-review-signals/)
  assert.match(styles, /\.trust-risk-lens/)
  assert.match(styles, /\.trust-decision-coach/)
})

test('Trust Center secondary panels include guidance and responsive session layout', () => {
  const batch = read('frontend/src/components/TrustBatchActionBar.vue')
  const loops = read('frontend/src/components/TrustOpenLoopPanel.vue')
  const diagnostics = read('frontend/src/components/TrustDiagnosticsPanel.vue')
  const styles = read('frontend/src/styles.css')

  assert.match(batch, /trust-batch-guidance/)
  assert.match(batch, /batchGuidance/)
  assert.match(loops, /trust-loop-priority-note/)
  assert.match(loops, /priorityNote/)
  assert.match(diagnostics, /trust-diagnostics-guidance/)
  assert.match(diagnostics, /diagnosticsGuidance/)
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.trust-session-planner/)
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.trust-decision-options/)
  assert.match(styles, /\.trust-batch-guidance/)
  assert.match(styles, /\.trust-loop-priority-note/)
  assert.match(styles, /\.trust-diagnostics-guidance/)
})

test('Trust Center exposes engine 3 analysis without adding visual pressure', () => {
  const view = read('frontend/src/components/TrustCenterView.vue')
  const detail = read('frontend/src/components/TrustReviewDetail.vue')
  const report = read('frontend/src/components/TrustQuietReport.vue')
  const digest = read('frontend/src/components/TrustAnalysisDigest.vue')
  const types = read('frontend/src/components/trustCenterTypes.ts')
  const styles = read('frontend/src/styles.css')

  assert.match(types, /TrustEngineAnalysis/)
  assert.match(types, /TrustSessionPayload/)
  assert.match(types, /TrustReportPayload/)
  assert.match(view, /TrustQuietReport/)
  assert.match(detail, /TrustAnalysisDigest/)
  assert.match(report, /trust-quiet-report/)
  assert.match(report, /<details/)
  assert.match(digest, /trust-analysis-digest/)
  assert.match(digest, /evidence_compression/)
  assert.match(styles, /\.trust-quiet-report/)
  assert.match(styles, /\.trust-analysis-digest/)
})
